class I2CDevice:
    def __init__(self, i2c, address): ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_value, traceback): ...
    def write(self, data): ...
    def readinto(self, buffer): ...


class I2C:
    def __init__(self): ...
